### ISSUE TITLE
BUG: Missing fields on response causes writeToStore Error

### ISSUE THREAD

**Issue by WilliamHolmes** [apollostack/apollo-client#263] opened 2016-06-03 10:40 UTC
ref: writeToStore.ts#L129

`Uncaught Error: Can't find field startCursor on result object some_group_id.people({"first":"10"}).pageInfo.
`
If a query response returns without values that were sent on the query, the client throws and error.

query
```javascript
query getGroup { 
  node(id: "some_group_id") {
    ... on Group {
      id
      people(first: 10) {
        pageInfo {
          hasNextPage
          hasPreviousPage
          startCursor
          endCursor
        }
      }
    }
  }
}
```

When there are no people in the group our server responses with ...

```javascript
... "pageInfo":{"hasNextPage":false,"hasPreviousPage":false} ...
```

Note in this case,  startCursor and endCursor are not returned

I'm not sure this should be considered and error or warning but the process should continue to write to store and return the client promise with the response data.

**Comment by stubailo** [comment] 2016-06-03 11:59
I don't think that is a valid GraphQL response for that query - what GraphQL server implementation are you using?

**Comment by WilliamHolmes** [comment] 2016-06-03 12:26
@stubailo [graphql-java](https://github.com/graphql-java/graphql-java)
I've opened an issue with our server guys in the meantime.

**Comment by stubailo** [comment] 2016-06-03 12:29
Oh ok I remember you also had an issue with the empty error array before. I heard that some people are working on a test suite to test GraphQL servers for spec compliance: https://github.com/graphql-cats/graphql-cats

**Comment by helfer** [comment] 2016-06-12 23:55
@WilliamHolmes Can you reference the issue you opened on graphql-java? I can't seem to find it there.

Also: closing this, since this is expected behavior when the server doesn't conform to the graphql spec.

**Closed by helfer** 2016-06-12 23:55 UTC
