### ISSUE TITLE
Cannot catch rejected fetchQuery promise after startQuery

### ISSUE THREAD

**Issue by jacobk** [apollostack/apollo-client#965] opened 2016-11-28 06:41 UTC
Should the promise returned inside `startQuery`[1]  be thrown away like this (returned from `fetchQuery`)? I've not studied the code enough to fully reason about it myself yet, but e.g. rejected promises on `resetStore`[2] seems to be impossible to handle atm.
 
Following the suggested logout use case of afterware[3] and resetStore[4] this seems to break all the time for me (logout in my case is dispatched through redux from inside the afterware).

[1] https://github.com/apollostack/apollo-client/blob/master/src/core/QueryManager.ts#L641
[2] https://github.com/apollostack/apollo-client/blob/master/src/core/QueryManager.ts#L615-L618
[3] http://dev.apollodata.com/core/network.html#networkInterfaceAfterware
[4] http://dev.apollodata.com/react/auth.html#login-logout (edited)

**Comment by helfer** [comment] 2016-11-28 21:22
@jacobk Thanks for reporting this. I think it's a duplicate of #891 which is fixed in #950.

**Closed by helfer** 2016-11-28 21:22 UTC

**Comment by DimitryDushkin** [comment] 2017-02-16 12:49
So how to catch this anyway?
