### ISSUE TITLE
The inline argument "perPage" is expected as a variable but was not provided.

### ISSUE THREAD

**Issue by ivan133** [apollostack/apollo-client#1183] opened 2017-01-16 06:26 UTC
Hi, guys.
I'm using apollo-client: 0.5.21 and graph.cool
I'm trying to get a list of guest to render it in table component (GuestsList)
I have this query:
```
export default graphql(allGuestsQuery, {
  options(ownProps) {
    return {
      // returnPartialData: true,
      variables: {
        filter: ownProps.filter,
        perPage: PER_PAGE_ITEMS,
        skip: 0,
        orderBy: DEFAULT_ORDER
      }
    };
  }})(GuestsList)
```
But when the page loads for the first time I got an error.
http://joxi.ru/l2ZnRMeIwzJNl2 
> The inline argument "perPage" is expected as a variable but was not provided.

Maybe this issue is connected with this one, but for me, it's looks like it's not
https://github.com/apollostack/apollo-client/issues/732

When I updated apollo-client to version 0.5.26 all works, but unfortunately I can't do it because this bug https://github.com/apollostack/apollo-client/issues/1129

**Comment by ivan133** [comment] 2017-01-16 06:28
I "Network" tab I can see that "perPage" is actually passed in request.
http://joxi.ru/a2XaZDOt1w8gVA

**Comment by curio77** [comment] 2017-01-19 16:36
Looks related to (my) #1163, too. Testing this now, I too see things going back and forth between the client and the GraphQL backend as expected, but still the error gets thrown and my component gets no data.

**Comment by calebmer** [comment] 2017-01-20 17:39
Could you see if this is fixed by https://github.com/apollostack/apollo-client/pull/1174?

**Comment by ivan133** [comment] 2017-01-24 06:48
@calebmer Sorry I didn't get it.
What version of apollo-client should I check?

**Comment by calebmer** [comment] 2017-01-24 20:16
Should be in `0.8.0` @ivan133 👍

**Comment by ivan133** [comment] 2017-01-25 20:11
@calebmer yes, looks it work. Although it also worked on 0.5.26.
The main issue for update was this https://github.com/apollostack/apollo-client/issues/1129
I'll check if it resolved on 0.8.0 later this week.

**Closed** 2017-01-25 20:11 UTC
Labels: bug

**Comment by thebigredgeek** [comment] 2017-02-23 07:06
This is still a major bug.  I am running 0.8.7 and have encountered it.  Looks like it happens if I SSR a page that uses a variable, navigate away from that page, and then navigate back to it via the back button.  It does NOT happen if I SSR a different page, navigate to the page, navigate away, and then navigate back.  It appears like it might have something to do a difference in query presentation during SSR?

**Comment by calebmer** [comment] 2017-02-23 19:19
@thebigredgeek could you reproduce your error with [`react-apollo-error-template`](https://github.com/apollographql/react-apollo-error-template)? It would go a long way in helping us debug the issue since we could really use some more information.
