### ISSUE TITLE
Getting exception when I reset the store

### ISSUE THREAD

**Issue by viridia** [apollostack/apollo-client#773] opened 2016-10-14 01:56 UTC
I'm not quite sure how to debug this. I'm getting an exception in this code in QueryManager:

```
forOwn(this.queryListeners, function (listeners, queryId) {
    listeners.forEach(function (listener) {
        if (listener) {
            var queryStoreValue = queries[queryId];
            listener(queryStoreValue);
        }
    });
});
```

Specifically, the 'listeners' variable is `undefined`. This occurs immediately after calling resetStore() - I'm doing a logout.

Any thoughts as to what might be causing this or how I might go about tracking it down?

**Comment by seeden** [comment] 2016-10-14 14:09
I have same issue with latest apollo-client@0.4.21. I can simulate it always with refetchQueries.

**Comment by seeden** [comment] 2016-10-14 15:21
My this.queryListeners looks like this: Object {0: Array[1], 8: Array[1]}
but in forEach I will get 3 cycles:
QueryManager.js:629 listeners [function] 0
QueryManager.js:629 listeners [function] 8
QueryManager.js:629 listeners undefined 1

**Comment by seeden** [comment] 2016-10-14 15:43
It looks like a bug in the forOwn because Object.keys(this.queryListeners) will return ["0", "8"]
or function listener on the line https://github.com/apollostack/apollo-client/blob/master/src/core/QueryManager.ts#L931 will change this.queryListeners. The second option is more likely

**Comment by helfer** [comment] 2016-10-14 19:14
@viridia @seeden thanks for reporting this and digging a bit deeper. I will set aside some time to figure out what's really going on and hopefully fixing the bug.

I'm pretty sure there's nothing wrong with forOwn, it might just be that the thing we're iterating over changes while we're iterating.

**Comment by seeden** [comment] 2016-10-18 14:34
@viridia I am using temporar fix for this issue because I was not able to continue in my work without it. 

Add next code
```js
if (!listeners) {
  return;
}
```

into the https://github.com/apollostack/apollo-client/blob/master/src/core/QueryManager.ts#L986

**Comment by seeden** [comment] 2016-10-19 14:17
This issue is still here in the 0.5.0-1

**Comment by seeden** [comment] 2016-10-19 14:23
It was OK in the version 0.4.20 but from 0.4.21 I can see this issue

**Comment by viridia** [comment] 2016-10-21 05:43
@seeden Yeah, it's getting hard to work as I am hitting this repeatedly.

**Comment by seeden** [comment] 2016-10-21 06:14
@stubailo can you add it into the 0.5 milestone?

**Comment by helfer** [comment] 2016-10-24 04:59
@seeden @viridia can either of you try to make a minimal reproduction or a failing test case for this? That would make it a lot easier for me to track it down.

**Comment by seeden** [comment] 2016-10-24 09:20
I will try to create test case today

**Comment by helfer** [comment] 2016-10-26 05:18
I put in a patch for this for now so it doesn't crash things any more. We'll track it down post 0.5

**Comment by viridia** [comment] 2016-10-30 22:33
OK I updated to the latest version I'll let you know if I see any more of these.

**Comment by viridia** [comment] 2016-11-06 17:56
Since updating to 0.5.0 I'm not seeing this anymore.

**Comment by helfer** [comment] 2016-11-08 22:38
Closing this since it seems to have been solved. If anyone runs into a similar issue, please also make sure that you're properly binding all the method calls to your Apollo Client instance where necessary, e.g. `client.methodX.bind(client)` .

**Closed by helfer** 2016-11-08 22:38 UTC
Labels: bug
