### ISSUE TITLE
react-native error is coming

### ISSUE THREAD

**Issue by gmchaturvedi1** [apollostack/apollo-client#289] opened 2016-06-21 18:14 UTC
Dear friends,

i am just trying apollo-client with react-native the following error is coming : 

![image](https://cloud.githubusercontent.com/assets/10846505/16241155/0c61fcca-380a-11e6-9ce0-b9c884ec29ef.png)

Kindly suggest me how to resolve this.

thanks & Regards
 G M Chaturvedi

**Comment by stubailo** [comment] 2016-06-21 18:18
Looks like a duplicate of this: https://github.com/apollostack/apollo-client/issues/163

It's weird that React Native is trying to compile this code at all. But let's talk on the other thread.

**Closed by stubailo** 2016-06-21 18:18 UTC
