### ISSUE TITLE
Typescript 2.0

### ISSUE THREAD

**Issue by danbucholtz** [apollostack/apollo-client#745] opened 2016-10-05 04:00 UTC
When I install this lib in a Typescript 2.0 app, I am stuck due to `@types` definitions missing.

Here is the output from Angular NGC.

```
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/middleware.d.ts:5:14: Cannot find name 'RequestInit'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/afterware.d.ts:1:1: Cannot find type definition file for 'isomorphic-fetch'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/afterware.d.ts:3:15: Cannot find name 'IResponse'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/afterware.d.ts:4:14: Cannot find name 'RequestInit'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/networkInterface.d.ts:1:1: Cannot find type definition file for 'typed-graphql'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/networkInterface.d.ts:2:1: Cannot find type definition file for 'chai'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/networkInterface.d.ts:3:1: Cannot find type definition file for 'isomorphic-fetch'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/networkInterface.d.ts:23:38: Cannot find name 'GraphQLResult'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/networkInterface.d.ts:30:46: Cannot find name 'GraphQLResult'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/networkInterface.d.ts:34:12: Cannot find name 'RequestInit'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/networkInterface.d.ts:42:14: Cannot find name 'RequestInit'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/networkInterface.d.ts:45:15: Cannot find name 'IResponse'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/networkInterface.d.ts:46:14: Cannot find name 'RequestInit'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/networkInterface.d.ts:52:12: Cannot find name 'RequestInit'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/networkInterface.d.ts:55:37: Cannot find name 'RequestInit'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/networkInterface.d.ts:58:77: Cannot find name 'IResponse'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/networkInterface.d.ts:59:38: Cannot find name 'GraphQLResult'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/networkInterface.d.ts:65:12: Cannot find name 'RequestInit'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/networkInterface.d.ts:68:110: Cannot find name 'RequestInit'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/queries/getFromAST.d.ts:1:1: Cannot find type definition file for 'typed-graphql'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/queries/getFromAST.d.ts:3:63: Cannot find name 'OperationDefinition'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/queries/getFromAST.d.ts:6:64: Cannot find name 'FragmentDefinition'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/queries/getFromAST.d.ts:7:60: Cannot find name 'OperationDefinition'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/queries/getFromAST.d.ts:8:63: Cannot find name 'FragmentDefinition'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/queries/getFromAST.d.ts:10:29: Cannot find name 'FragmentDefinition'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/queries/getFromAST.d.ts:12:55: Cannot find name 'FragmentDefinition'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/queries/getFromAST.d.ts:13:79: Cannot find name 'FragmentDefinition'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/queries/store.d.ts:1:1: Cannot find type definition file for 'chai'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/queries/store.d.ts:3:1: Cannot find type definition file for 'typed-graphql'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/queries/store.d.ts:20:20: Cannot find name 'GraphQLError'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/queries/store.d.ts:29:19: Cannot find name 'SelectionSet'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/data/scopeQuery.d.ts:1:1: Cannot find type definition file for 'typed-graphql'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/data/scopeQuery.d.ts:10:19: Cannot find name 'SelectionSet'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/data/scopeQuery.d.ts:13:5: Cannot find name 'SelectionSet'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/data/mutationResults.d.ts:1:1: Cannot find type definition file for 'typed-graphql'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/data/mutationResults.d.ts:2:1: Cannot find type definition file for 'chai'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/data/mutationResults.d.ts:27:24: Cannot find name 'SelectionSet'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/data/mutationResults.d.ts:28:21: Cannot find name 'FragmentDefinition'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/data/mutationResults.d.ts:34:13: Cannot find name 'GraphQLResult'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/data/mutationResults.d.ts:37:19: Cannot find name 'SelectionSet'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/actions.d.ts:1:1: Cannot find type definition file for 'typed-graphql'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/actions.d.ts:3:1: Cannot find type definition file for 'chai'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/actions.d.ts:10:13: Cannot find name 'GraphQLResult'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/actions.d.ts:39:13: Cannot find name 'GraphQLResult'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/actions.d.ts:62:13: Cannot find name 'GraphQLResult'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/actions.d.ts:76:24: Cannot find name 'SelectionSet'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/actions.d.ts:77:21: Cannot find name 'FragmentDefinition'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/mutations/store.d.ts:1:1: Cannot find type definition file for 'chai'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/mutations/store.d.ts:3:1: Cannot find type definition file for 'typed-graphql'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/mutations/store.d.ts:21:19: Cannot find name 'SelectionSet'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/data/extensions.d.ts:1:1: Cannot find type definition file for 'chai'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/queries/queryTransform.d.ts:1:1: Cannot find type definition file for 'typed-graphql'.
Error at /Users/dan/Dev/rollup-lib-issues/mega-lib-trail/node_modules/apollo-client/queries/queryTransform.d.ts:3:55: Cannot find name 'SelectionSet'.
```

This issue is submitted on behalf of @metzc and his issue using this library with Ionic.
https://github.com/driftyco/ionic-app-scripts/issues/67#issuecomment-251217721

Thanks,
Dan

**Comment by stubailo** [comment] 2016-10-12 23:35
I think this is a duplicate of #713 but I think there are some issues with that approach as well.

**Closed by stubailo** 2016-10-12 23:35 UTC
Labels: feature
