### ISSUE TITLE
Don't error if optional field not present

### ISSUE THREAD

**Issue by deoqc** [apollostack/apollo-client#561] opened 2016-08-19 09:00 UTC
Sometimes I have a form with not all fields required, and it will be used as inputs to a mutation.

``` Javascript
const query = gql`
  mutation myForm(
    $name: String!
    $tags: [String!]
  ) {
    createSomethingAwesome(
      name: $name
      tags: $tags
    ) {
       id
       someField
    }
`
```

But I actually need to pass an empty `tags` to `variables`. If I pass only `variables: { name }` it will error.

Should `apollo-client` take care of this? 

Right now I'm doing `variables: { tags: [], ...formFields }` instead of `variables: formFields` since `formFields` won't have `tags` key if it is empty.

**Comment by stubailo** [comment] 2016-08-19 21:24
I don't think Apollo Client should take care of this. IMO the correct way to solve this is to pass `tags: null` as a variable. Is that an acceptable solution? I consider this a limitation of GraphQL itself, rather than Apollo Client, and the workaround doesn't seem so bad.

**Comment by stubailo** [comment] 2016-08-19 21:25
Perhaps we could analyze the variables and automatically pass `null` for ones that the developer doesn't pass, but I think that would actually be worse than the current behavior, which at least warns you when you forget to pass a variable.

Although, perhaps we could use the nullability `!` to determine if we should pass `null` by default.

**Comment by deoqc** [comment] 2016-08-19 21:35
Yeah, the thing is the field is optional and if you don't pass it is not warn, it is an error. 

I can always pass the empty/null args, as I am doing now, but I wondered if wouldn't it be a feature `apollo-client` would like to have. I have no argument against if you think that wouldn't.

**Comment by stubailo** [comment] 2016-08-19 22:13
My only reservation is that it's more code to maintain, so if it's not super valuable it might not be worth it.

**Comment by webular** [comment] 2016-08-19 22:58
Heres how we approached it.  Not sure this is correct but it solved that issue for us. 

We found that we needed to change my mutation schema on the server to use `GraphQLInputObjectType`:  More info here: [http://graphql.org/docs/api-reference-type-system/#graphqlinputobjecttype](http://graphql.org/docs/api-reference-type-system/#graphqlinputobjecttype)

Then in your mutation schema you'd define formInput as a GraphQLInputObjectType.  Finally client  side your mutation would look something like this: 

`mutation myForm(
    $formInput: formInput!
  ) {
    createSomethingAwesome(
      formInput: $formInput
    ) {
       id
       someField
    }`

Hope that works.

**Comment by deoqc** [comment] 2016-08-19 23:19
@webular it's a good approach, just tested and it works. 

But I usually prefer just use `GraphQLInputObjectType` when some input just make sense when grouped (like `geocode={lat, lon}`), but it clearly shows that if you really want this feature, you could get it *somehow* from the GraphQL specs. 

I think I can close it now @stubailo .

**Comment by stubailo** [comment] 2016-08-19 23:26
OK, works for me!

**Comment by deoqc** [comment] 2016-08-20 01:33
I don't want to be annoying but just saw that `graphiql` doesn't error in my situation above, I think it is a `apollo-client` trait.

**Comment by stubailo** [comment] 2016-08-20 03:43
Ok in that case it might be a bug.

**Comment by deoqc** [comment] 2016-09-21 21:10
Any update about this (possible) bug?

**Comment by helfer** [comment] 2016-09-21 21:23
@deoqc This is not a high priority for us at the moment, but if you submit a PR with a failing test case, it would help us fix it faster.

**Comment by deoqc** [comment] 2016-09-21 21:32
Ok will look into it. 

Just asked 'cause it is annoying/error prone to always fill missing optional variables, and have this inconsistent behaviour between apollo and graphiql.

**Comment by glasser** [comment] 2016-11-30 21:44
I've been reading the GraphQL spec and it doesn't really seem clear about whether or not leaving off the value for a variable which is null is allowed or not.  However, the NOTE in https://facebook.github.io/graphql/#sec-Null-Value does suggest that it should be allowed:

> The same two methods of representing the lack of a value are possible via variables by either providing the a variable value as null and not providing a variable value at all.

**Comment by glasser** [comment] 2016-11-30 21:48
Although maybe this is a duplicate of #852, which refers to https://github.com/facebook/graphql/pull/83 which only added the concept of null-ness to GraphQL after the discussion in this issue!

**Comment by helfer** [comment] 2016-11-30 23:36
@glasser: yes, this is something that I will need to add to the 1.0 roadmap. Thanks for the reminder!

**Comment by helfer** [comment] 2016-12-05 17:11
Closing this in favor of #852

**Closed by helfer** 2016-12-05 17:11 UTC
Labels: feature, help wanted
