### ISSUE TITLE
Old reducers still re-run

### ISSUE THREAD

**Issue by Siyfion** [apollostack/apollo-client#993] opened 2016-12-05 12:03 UTC
I think this might be related to #960 or potentially #930 but it's not the same as either.

I believe that the issue is caused by "old" reducers still being re-run even though they are marked as old, causing a "double" (or more) firing of the event.

Symptoms: 

I have a component that is created when the user navigates to a particular route, if I delete an item on that page the `reducer` fires once and updates the query's previous result and removed the deleted item from the results set.
If I leave that route (unmounting the component) and re-enter it again, upon deletion the `reducer` will fire twice, attempting to remove the result twice. As I hadn't originally foreseen the item never being there, the `_.findIndex` call returned -1 on the second trigger then removed a second item (one that actually *hadn't* been deleted!).

I've mentioned this to @helfer and he suggested making an issue here..

**Comment by helfer** [comment] 2016-12-13 05:49
@Siyfion can you test if this is fixed now?

**Comment by Siyfion** [comment] 2016-12-13 10:32
@helfer Just tested with `apollo-client v0.5.19` and no... This isn't fixed.

**Comment by helfer** [comment] 2016-12-13 12:07
@Siyfion okay, in that case I will need a bit more information, ideally a minimal reproduction or a failing test case.

**Comment by SachaG** [comment] 2016-12-15 14:27
I can confirm I'm running into the same issue. I have a list of posts on my homepage, and inserting posts into it works fine. 

But if I go to another page (which unmounts the post list), come back, and try inserting again, I get a `Encountered two children with the same key` React error because the new document was inserted twice. And if I got back and forth 5 extra times, I'll now have 5 extra documents in my list (and thus 5 errors).

If you want to test it out you can pull the latest version of Nova: https://github.com/TelescopeJS/Telescope/tree/apollo

**Comment by helfer** [comment] 2016-12-17 15:30
Should be fixed in 0.5.22.

**Closed by helfer** 2016-12-17 15:30 UTC

**Comment by SachaG** [comment] 2016-12-18 08:51
Awesome, thanks so much!
