### ISSUE TITLE
Exception after mutation when using reducer vs updateQueries

### ISSUE THREAD

**Issue by yurigenin** [apollostack/apollo-client#890] opened 2016-11-09 23:21 UTC
`writeToStore.js:163 Uncaught Error: Store error: the application attempted to write an object with no provided id but the store already contains an id of Customer1 for this object.`

I'm getting this exception but only when using reducer on a query instead of updateQueries on mutation. The problem seems to be that when the updateQueries is called all the nested objects in the 'prev' parameter have their __typename field present. But when the reducer is called the same nested objects in the 'prev' parameter are missing the __typename field. Thus, the exception.

**Comment by yurigenin** [comment] 2016-11-09 23:26
Looks like it is exactly the same issue as #870

**Comment by helfer** [comment] 2016-11-09 23:41
Closing this as a duplicate of #870

**Closed by helfer** 2016-11-09 23:41 UTC
Labels: bug
