### ISSUE TITLE
Network error: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by drFabio** [apollostack/apollo-client#834] opened 2016-10-24 21:14 UTC
On Apollo client I am receiving this message: 
`Network error: Cannot read property 'forEach' of undefined` I pinpointed to the root cause being that "listeners" is undefined [here](https://github.com/apollostack/apollo-client/blob/afcc478b1ccd4142e6d0ffb78d924fe76bc47877/src/core/QueryManager.ts#L987) .

I checke dthe network of My queries and they are successfullu resolved , also replaying them on graphiql works as expected. Is there any reason fot this variable to be undefined ?

**Comment by drFabio** [comment] 2016-10-24 21:18
Also checking for an undefined listeners and returning apparently fix the behaviour. Do not know the cause yet

**Comment by helfer** [comment] 2016-10-24 21:31
Thanks for reporting, I'll close this as a likely duplicate of #833. I might put in the patch/workaround until I can pinpoint the root cause.

**Closed by helfer** 2016-10-24 21:31 UTC

**Comment by thebigredgeek** [comment] 2016-12-16 00:12
Also seeing this. 0.4.21

**Comment by stubailo** [comment] 2016-12-16 00:14
0.4 or 0.5? 0.4.x is pretty old so I wouldn't be surprised if the issue was still present there.

**Comment by thebigredgeek** [comment] 2016-12-16 00:15
Yeah just updated.
