### ISSUE TITLE
Cannot read property 'forEach' of undefined in broadcastQueries

### ISSUE THREAD

**Issue by bkniffler** [apollostack/apollo-client#833] opened 2016-10-24 16:35 UTC
Hey, 
I wonder if this is related to https://github.com/apollostack/apollo-client/issues/830

If there are errors thrown on the server, the crashReporter in store.js catches an exception from QueryManager with the following stacktrace:

```
QueryManager.js:579 Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined
    at eval (webpack:////Users/bkniffler/Documents/Projekte/nodejs/~/apollo-client/core/QueryManager.js?:579:22)
    at eval (webpack:////Users/bkniffler/Documents/Projekte/nodejs/~/lodash.forown/index.js?:161:11)
    at baseForOwn (webpack:////Users/bkniffler/Documents/Projekte/nodejs/~/lodash.forown/index.js?:122:20)
    at forOwn (webpack:////Users/bkniffler/Documents/Projekte/nodejs/~/lodash.forown/index.js?:447:20)
    at QueryManager.broadcastQueries (webpack:////Users/bkniffler/Documents/Projekte/nodejs/~/apollo-client/core/QueryManager.js?:578:9)
    at Array.eval (webpack:////Users/bkniffler/Documents/Projekte/nodejs/~/apollo-client/core/QueryManager.js?:47:23)
    at dispatch (webpack:////Users/bkniffler/Documents/Projekte/nodejs/~/redux/lib/createStore.js?:186:19)
    at Object.eval [as dispatch] (webpack:////Users/bkniffler/Documents/Projekte/nodejs/~/apollo-client/store.js?:10:16)
    at eval (webpack:////Users/bkniffler/Documents/Projekte/nodejs/~/apollo-client/core/QueryManager.js?:545:33)
```

```
 QueryManager.prototype.broadcastQueries = function () {
        var queries = this.getApolloState().queries;
        forOwn(this.queryListeners, function (listeners, queryId) {
            listeners.forEach(function (listener) { // listeners is undefined
                if (listener) {
                    var queryStoreValue = queries[queryId];
                    listener(queryStoreValue);
                }
            });
        });
    };
```

**Comment by stubailo** [comment] 2016-10-24 16:55
If you have a moment, could you send a PR with a failing test?

**Comment by helfer** [comment] 2016-10-24 17:57
This sounds a lot like #773. Are you using resetStore by any chance?

**Comment by drFabio** [comment] 2016-10-25 11:08
I had a simillar behaviour, Unfortunately I could not isolate nor provide a failing test. What I did have is some new info. First of all checking for listeners to be undefined apparently solved it as I mentioned on https://github.com/apollostack/apollo-client/issues/834 

But analyzing the code I thought that to be strange because even with an empty object _.forOwn should not return that.

I think **this is a race condition**, another solution that I found gave me the same behaviour as checking the listeners var for undefined was cloning this.queryListeners

```javascript
  QueryManager.prototype.broadcastQueries = function () {
        var queries = this.getApolloState().queries;
        var queryListeners = Object.assign({},this.queryListeners)
        forOwn(queryListeners, function (listeners, queryId) {
            if(!listeners){
                return
            }
            listeners.forEach(function (listener) {
                if (listener) {
                    var queryStoreValue = queries[queryId];
                    listener(queryStoreValue);
                }
            });
        });
    };
````
On my code I am embedding 2 objects on graphql and they use common fragments and they both make two queries on the same  (perhaps it's related , don't know). Will try to work on an isolated minimal example

**Comment by bkniffler** [comment] 2016-10-25 16:31
I wasn't able to reproduce it in an isolated project/test, but when I replace the broadcastQueries with @drFabio s code, the problem disappears.

**Comment by helfer** [comment] 2016-10-25 17:45
Okay, I will put that patch in until we find and fix the root cause.

**Comment by bkniffler** [comment] 2016-10-26 07:01
It seems like the errors don't appear in console any more, but the whole query still fails. Say I have 4 batched queries and one fails due to a server-side error, the other queries won't persist their data to the store. I'll check if I can find out more, but I'm a bit busy atm.

**Comment by drFabio** [comment] 2016-10-26 11:05
Will check the patch now. So @bkniffler  this is a batch query issue only? Yeah mine was not much of a patch and more of a test to see where the problem was made present. Did you tried with the Object.assign() ? I did not test for failing queries also

**Comment by helfer** [comment] 2016-11-08 22:39
Can someone here comment on whether this is still happening? If it is, I would appreciate a repro or failing test.

**Comment by bkniffler** [comment] 2016-11-09 00:15
I tried to isolate the issue, but it was hard to reproduce. I didn't have any more issues in my projects since the patch though, so I'm okay with closing this if you guys are. I'll keep a close eye on my console.

**Comment by drFabio** [comment] 2016-11-09 00:28
I couldn't isolate it but I think cloning is the best approach than
checking undefined. A similar issue seems to be related to the race
condition and it seems cloning would be more fail proof. But then again
without a failing test there is no proof to that

**Comment by helfer** [comment] 2016-12-05 14:33
Closing since it's been a month since the last observation of this bug in the wild.

**Closed by helfer** 2016-12-05 14:33 UTC
