### ISSUE TITLE
Webpack, Angular CLI and Apollo-Client

### ISSUE THREAD

**Issue by LibertyBeta** [apollostack/apollo-client#553] opened 2016-08-18 02:44 UTC
Current, Apollo-Client doesn't build correctly when using webpack and the currently Angular CLI. Its seems unable to find both `graphql` and `RequestInit`.

These, while not completely breaking, do make certain functions like observable queries fail to load properly.

**Comment by stubailo** [comment] 2016-08-19 21:26
Can you create and post a reproduction? That will let us identify the specific issue you are running into.

**Comment by kamilkisiela** [comment] 2016-08-20 15:08
@stubailo It's probably related to #207.
`apollo-client` doesn't depend on `graphql` so it's the TypeScript thing.

I follow _apollostack/angular2-apollo_ repository so if there's something related to Angular, feel free to @mention me :)

@LibertyBeta run:

```
typings i -S graphql

typings i -SG dt~isomorphic-fetch
```

`RequestInit` is related to `fetch` so you have to add typings for it

**Comment by LibertyBeta** [comment] 2016-08-20 15:43
@kamilkisiela I'll give that a go. The repo is [Apollo-Hive](https://github.com/LibertyBeta/Apollo-Hive)

**Comment by LibertyBeta** [comment] 2016-08-28 19:21
So, I've updated the repo and queries/etc, are working. However I still can't resolve the graphql typing issue.

**Comment by kamilkisiela** [comment] 2016-08-28 20:11
If you have installed typings for `graphql` and you still have an issue, it's probably because your configuration doesn't include this declaration. Try to add `/// reference` to some `d.ts` file that is visible by `angular-cli`. If I remember correctly there is a `typings.d.ts` in one of the directories. 

By `/// reference` I mean:

```
/// <reference path="path/to/graphql/index.d.ts" />
```

**Comment by LibertyBeta** [comment] 2016-08-28 22:01
I ended up having to use the `@types/isomorphic-fetch` npm package to get the fetch working. Just installing the typings seems to do nothing.

**Comment by kamilkisiela** [comment] 2016-08-28 22:06
It's because the build tool which in your case is angular-cli that is based on webpack doesn't now there are any typings. That's why I gave you instructions how to do that. Why it knows about `@types/isomorphic-fetch`? Because it's been configured this way. There's no `@types/graphql` yet so you have to use declaration installed by `typings`

**Comment by LibertyBeta** [comment] 2016-08-28 22:13
Which CLI doesn't seem to be honoring. I'll head over to the Gitter for CLI and see if they can shed any light.

**Comment by stubailo** [comment] 2016-09-02 05:12
Any updates on this?

**Comment by kamilkisiela** [comment] 2016-09-02 06:56
@stubailo Everything works. I even prepared a demo for a webinar based on `angular-cli`, `apollo-client` and `angular2-apollo`. So as I said before: only thing to do is to install declarations for `graphql` from `dt` source and include them in any d.ts file that typescript could see.

You can close it.

**Comment by kamilkisiela** [comment] 2016-09-02 07:27
Webpack version of Angular-CLI uses typescript 2.0 with `@types/*` as the only source of declarations and since there is no `@types/graphql` package I think the best solution is to add main entry point of typings which is `typinigs/index.d.ts` in the root directory. This way you can install all declarations that are not under `@types`.

**src/typings.d.ts**
```
/// <reference path="../typings/index.d.ts" />
declare var System: any;
```

**Comment by LibertyBeta** [comment] 2016-09-02 13:11
Can confirm, manually including the typings file works withe most recent CLI builds. I still throws a NodeJS namespace issue, but it works without a page of issues.

**Comment by kamilkisiela** [comment] 2016-09-03 04:00
So why don't you use `@types/node`?

**Comment by LibertyBeta** [comment] 2016-09-03 04:04
Using `@types/node` was causing some issues with the CLI last I checked. And manually including the typings JUST started working as of the most recent webpack build for me.

**Comment by Muffasa** [comment] 2016-09-03 12:48
any update on this?
after resolving the graphql typings and installing `@types/node` I stilll have those errors:

```
 ERROR in [default] /home/kimchi/learning/apollo/client/angular2-apollo-starter/node_modules/apollo-client/QueryManager.d.ts:23:27 
Cannot find namespace 'NodeJS'.

ERROR in [default] /home/kimchi/learning/apollo/client/angular2-apollo-starter/node_modules/apollo-client/afterware.d.ts:2:14 
Cannot find name 'IResponse'.

ERROR in [default] /home/kimchi/learning/apollo/client/angular2-apollo-starter/node_modules/apollo-client/afterware.d.ts:3:13 
Cannot find name 'RequestInit'.
```

**Comment by davd33** [comment] 2016-09-18 12:11
I also still have the "Cannot find namespace 'NodeJS'." error message after fixing the other ones.

**Closed** 2016-12-05 14:51 UTC
Labels: needs-repro
