### ISSUE TITLE
Inline fragments not supported everywhere

### ISSUE THREAD

**Issue by deoqc** [apollostack/apollo-client#147] opened 2016-04-25 13:12 UTC
I already have GraphQL server (w/ express), and I am currently using Relay to connect it (also already have a Redux store, for client state). 'Cause Relay is too complex/hard-to-be-confident, I followed the path to integrate my Redux store to Apollo Client, but my app crashes with the following:

$export is not a function. (In '$export($export.S + $export.F * !require(1245 /* ./_descriptors */), 'Object', { defineProperty: require(1240 /* ./_object-dp */).f })', '$export' is an instance of Object)
in file: app/node_modules/graphql/node_modules/core-js/library/modules/es6.object.define-property.js

Running on React-Native 0.23.1, GraphQL 0.5.0.

Any clues?

**Comment by stubailo** [comment] 2016-04-25 18:16
Hmm, could you post some of your code? Perhaps it is something specific to React Native, it's pretty hard to see what is going on from that error, though.

**Comment by deoqc** [comment] 2016-04-25 20:20
I only connected the apollo to the store, didn't do anything else (see bellow). But the app crashes if have this code.

Maybe could be some conflict with Relay? [This is the Relay example](https://github.com/facebook/relay/tree/master/examples/TodoMVC) I followed to get it to work with React Native. For example, [this is the .babelrc](https://github.com/facebook/relay/blob/master/examples/TodoMVC/.babelrc) that I had to use.

---

Create Apollo Client (file Apollo.js):
```Javascript
import { ApolloClient, createNetworkInterface } from 'apollo-client';
const networkInterface = createNetworkInterface('http://localhost:8080/graphql');

export default new ApolloClient({
  networkInterface,
});
```

Connect to the store:
```Javascript
...
import apolloClient from '../Apollo';
import { combineReducers } from 'redux';

const apollo = apolloClient.reducer();

export default combineReducers({
  ...
  apollo,
});
```

Manually install runtime-plugin (error if don't):
```Javascript
"babel-plugin-transform-runtime": "6.6.0",
```

**Comment by martijnwalraven** [comment] 2016-04-26 22:12
I was able to reproduce this error and finally managed to get it to work. I still don't fully understand the issue, but it seems it has to do with using Babel 6 with React Native's Packager (see https://github.com/facebook/react-native/issues/4062).

```
rm -rf node_modules
npm install
npm install babel-plugin-transform-runtime@6.6.0
npm install babel-preset-es2015@6.6.0
```

At one point, the packager seemed to get stuck on resolving dependencies, what fixed this was:
```
watchman watch-del-all
node_modules/react-native/packager/packager.sh --reset-cache
```

**Comment by deoqc** [comment] 2016-04-28 13:12
@martijnwalraven I had no success following your steps, but I mocked the data, removed relay and its dependencies (from babel, plugin, etc) and the started using Apollo client successfully. The problem must lie in some conflict with its babel dependency as you suggested (my initial hypothesis also).

Now the problem is that I used the Node Interface to fetch data from different types, which it doesn't seem (yet?) possible with Apollo. Like so:

```Javascript
const mapQueriesToProps = ({ownProps: { id }}) => ({
  data: {
    query: `
      query getSomeData($id: ID!) {
        node(id: $id) {
          id
          ... on SomeType {
            first_field
            second_field
          }
        }
      }
    `,
    variables: {
      id,
    },
    forceFetch: false,
    returnPartialData: true,
  },
});
```

@stubailo Is this feature in the pipeline for the short-term or should I implement a route to have a query for each different types of Node I previously had?

**Comment by helfer** [comment] 2016-04-28 15:44
@deoqc I'm not sure how you were doing it before, but you should be able to build the equivalent of a node interface, if you use a GraphQL Union and define the resolveType.

**Comment by deoqc** [comment] 2016-04-28 18:55
@helfer doesn't GraphQL Union requires fragments the same way that Node Interface do? (reading the fb [docs](https://facebook.github.io/graphql/#sec-Unions)).

In this case, I think I can't use Union for the same reason that I can't use Interface in Apollo, due to lack of fragment support.

**Comment by helfer** [comment] 2016-04-28 19:04
Pretty sure you can use inline fragments with apollo-client, just not named fragments. The fragment in the example above is an inline fragment. @stubailo: please correct me if I'm wrong.

**Comment by deoqc** [comment] 2016-04-28 19:11
@helfer when I tried (as of apollo-client@0.1.6) I got something like 'inline fragments not yet supported'.

**Comment by stubailo** [comment] 2016-04-28 20:01
I thought we supported fragments but it turns out we don't everywhere! Going to fix that ASAP!

**Comment by deoqc** [comment] 2016-04-28 20:03
thx @stubailo, going to wait for it. (and closed the issue by mistake)

**Closed** 2016-05-05 18:27 UTC
Labels: bug
