### ISSUE TITLE
using apollo with rethinkdb horizon

### ISSUE THREAD

**Issue by fortm** [apollostack/apollo-client#257] opened 2016-05-30 10:10 UTC
Can apollo-client be used with RethinkDb horizon client  [horizon](http://horizon.io/) in a react/redux app as horizon is going to support GraphQL queries as well directly from client to database ?

**Comment by helfer** [comment] 2016-05-30 16:23
Apollo-client can be used with any spec-compliant GraphQL server.

**Comment by stubailo** [comment] 2016-05-30 17:16
As far as I know, graphql support in horizon is not implemented yet, but when it is Apollo Client should work out of the box!

**Comment by Poincare** [comment] 2016-05-31 04:46
Yup, seems like it is an open issue on their end (https://github.com/rethinkdb/horizon/issues/125).

**Comment by stubailo** [comment] 2016-06-02 12:27
Gonna close this since the issue is not on our end - its up to horizon to implement a graphql server.

**Closed by stubailo** 2016-06-02 12:27 UTC
