### ISSUE TITLE
resultTransformer use cases

### ISSUE THREAD

**Issue by nevir** [apollostack/apollo-client#1150] opened 2017-01-09 18:09 UTC
We're still using `resultTransformer` (heh, I was in the middle of [writing a PR](https://github.com/apollostack/apollo-client/pull/1151) to fix it right as you merged 0.7)

Our use case is to [wrap result nodes in prototypes](https://github.com/apollostack/apollo-client/blob/748fa72ee1c23d5bb1e6534e2f7dba32cb5a31e7/test/QueryManager.ts#L3418) (e.g. by `__typename`), before they're returned by apollo-client.  We hang (stateless) business logic off of those prototyped nodes.

It also appears to be a good use case for other transformations (think middleware), like deep freezing results.  It'd also let you more easily expose the deep-freeze-in-dev behavior as an option (rather than the forced opt-in it is now; but I dunno if anyone would actually turn it off, anyway).

---

My argument for this being part of apollo-client - as opposed to something that wraps the client - is that it's hard to get right.  

There are various locations where apollo-client emits data, and they're easy to miss. See, for example, #1151 - the deep freezing logic missed a spot.  Monkey patching them all would be quite painful.

**Comment by helfer** [comment] 2017-01-10 04:58
@nevir Ok, let me think about it for a while. I see the benefit of having it in apollo-client, but at the same time it's something that very very few people are using. The main reason I even thought of deprecating `resultTransformer` was because it isn't called in `getCurrentQueryResult`, which suggested to me that it wasn't really working as intended. Since nobody filed a bug about it I assumed that nobody was using it.

**Comment by nevir** [comment] 2017-01-10 14:41
> Since nobody filed a bug about it I assumed that nobody was using it.

Yeah, I have a hunch that my team is the only use of it at the moment - we've been stuck on an older build of apollo-client for a while, and are just upgrading now :(

**Comment by helfer** [comment] 2017-01-12 05:43
@nevir Okay, thanks! In that case I would prefer to have it outside of Apollo Client because it adds more code to maintain for no benefit to the majority of users. We're thinking about doing some bigger refactoring though, so we'll see where we land on this once we have an idea of what the core is going to look like.

**Comment by nevir** [comment] 2017-01-12 21:23
👍

**Comment by nevir** [comment] 2017-01-12 21:24
Would it be ok to merge #1151 this in the meantime, until you fully deprecate?

**Comment by calebmer** [comment] 2017-01-20 17:26
I’m going to close this and let the discussion continue in https://github.com/apollostack/apollo-client/pull/1151. Hopefully, as we try to make the interface more uniform then transforming results will be much easier to get right 👍

**Closed by calebmer** 2017-01-20 17:26 UTC
