### ISSUE TITLE
Component hierarchy including queries and apollo

### ISSUE THREAD

**Issue by smolinari** [apollostack/apollo-client#152] opened 2016-04-26 04:10 UTC
With React and Relay, a developer can add GraphQL query fragments in each React component and Relay understands to build a hierarchy of the required data in the store.

https://facebook.github.io/relay/docs/guides-containers.html#containers-are-higher-order-components
https://facebook.github.io/relay/docs/thinking-in-relay.html#data-components-aka-containers

I read that the apollo-client aims to have "Query aggregation from your UI tree". Is the meaning the same thing?

Scott

**Comment by stubailo** [comment] 2016-04-26 04:18
Duplicate of #148 

Yep, that's the same thing!

**Closed by stubailo** 2016-04-26 04:18 UTC

**Comment by smolinari** [comment] 2016-04-26 04:39
Thanks for the clarification!

Scott
