### ISSUE TITLE
How to use Polling + Pagination

### ISSUE THREAD

**Issue by jimmiebtlr** [apollostack/apollo-client#1121] opened 2017-01-04 17:08 UTC
How should this work?

```
const fetchHOC = graphql(fetchBotGQL, {
  options: () => ({
    pollInterval: 1000, // ms to poll
    variables: {
      offset: null,
      limit: null,
    },
  }),
  props({ data: { loading, fetchMore }, ownProps }) {
    return {
      ...ownProps,
      loading,
      doc,
      loadMoreEntries({ startDocIndex, endDocIndex }) {
        return fetchMore({
          variables: {
            limit: endDocIndex - startDocIndex,
            offset: startDocIndex,
          },
          updateQuery: (previousResult, { fetchMoreResult }) => {
            if (!fetchMoreResult.data) { return previousResult; }
            const arraySize = endDocIndex > previousResult.bot.events.length ? endDocIndex : previousResult.doc.events.length;
            const events = new Array(arraySize);
            previousResult.doc.events.forEach((e, i) => { events[i] = e; });
            fetchMoreResult.data.doc.events.forEach((e, i) => {
              events[i + startDocIndex] = e;
            });

            return Object.assign({}, previousResult, {
              // Append the new dialogs results to the old one
              doc: {
                ...previousResult.doc,
                events,
              },
            });
          },
        });
      },
    };
  },
});
```

It looks like every time the poll hit's, it completely overwrites the other fetch more portion of things.  Is there any way to have the primary query just update query instead of overwriting?

**Comment by helfer** [comment] 2017-01-05 04:52
@jimmiebtlr I think this is a duplicate of #1087. The short answer is that they weren't intended to be used together. I thought we had a warning at some point, but it seems that's not the case any more, so we should add it back in.

**Closed by helfer** 2017-01-05 04:52 UTC

**Comment by tcoughlin3** [comment] 2018-10-10 17:50
Are there any current or future plans to support polling + pagination?

**Comment by adamsoffer** [comment] 2019-10-18 21:26
So if you use polling you can't paginate?

**Comment by mattlysf** [comment] 2021-02-09 20:06
Is polling + pagination still unsupported? If so, this still isn't documented.
