### ISSUE TITLE
Property undefined error in type definitions.

### ISSUE THREAD

**Issue by Axure** [apollostack/apollo-client#800] opened 2016-10-18 17:26 UTC
## Steps to Reproduce

Just import `apollo-client`.
### Buggy Behavior

```
[0] /home/zhenghu/coding/qsc/qsc-main-react-typescript/node_modules/apollo-client/index.d.ts
[0] (47,18): error TS2459: Type '{ networkInterface?: NetworkInterface | undefined; reduxRootKey?: string | undefined; reduxRootSe...' has no property 'networkInterface' and no string index signature.
[0] /home/zhenghu/coding/qsc/qsc-main-react-typescript/node_modules/apollo-client/index.d.ts
[0] (47,36): error TS2459: Type '{ networkInterface?: NetworkInterface | undefined; reduxRootKey?: string | undefined; reduxRootSe...' has no property 'reduxRootKey' and no string index signature.
[0] /home/zhenghu/coding/qsc/qsc-main-react-typescript/node_modules/apollo-client/index.d.ts
[0] (47,50): error TS2459: Type '{ networkInterface?: NetworkInterface | undefined; reduxRootKey?: string | undefined; reduxRootSe...' has no property 'reduxRootSelector' and no string index signature.
[0] /home/zhenghu/coding/qsc/qsc-main-react-typescript/node_modules/apollo-client/index.d.ts
[0] (47,69): error TS2459: Type '{ networkInterface?: NetworkInterface | undefined; reduxRootKey?: string | undefined; reduxRootSe...' has no property 'initialState' and no string index signature.
[0] /home/zhenghu/coding/qsc/qsc-main-react-typescript/node_modules/apollo-client/index.d.ts
[0] (47,83): error TS2459: Type '{ networkInterface?: NetworkInterface | undefined; reduxRootKey?: string | undefined; reduxRootSe...' has no property 'dataIdFromObject' and no string index signature.
[0] /home/zhenghu/coding/qsc/qsc-main-react-typescript/node_modules/apollo-client/index.d.ts
[0] (47,101): error TS2459: Type '{ networkInterface?: NetworkInterface | undefined; reduxRootKey?: string | undefined; reduxRootSe...' has no property 'queryTransformer' and no string index signature.
[0] /home/zhenghu/coding/qsc/qsc-main-react-typescript/node_modules/apollo-client/index.d.ts
[0] (47,119): error TS2459: Type '{ networkInterface?: NetworkInterface | undefined; reduxRootKey?: string | undefined; reduxRootSe...' has no property 'resultTransformer' and no string index signature.
[0] /home/zhenghu/coding/qsc/qsc-main-react-typescript/node_modules/apollo-client/index.d.ts
[0] (47,138): error TS2459: Type '{ networkInterface?: NetworkInterface | undefined; reduxRootKey?: string | undefined; reduxRootSe...' has no property 'resultComparator' and no string index signature.
[0] /home/zhenghu/coding/qsc/qsc-main-react-typescript/node_modules/apollo-client/index.d.ts
[0] (47,156): error TS2459: Type '{ networkInterface?: NetworkInterface | undefined; reduxRootKey?: string | undefined; reduxRootSe...' has no property 'shouldBatch' and no string index signature.
[0] /home/zhenghu/coding/qsc/qsc-main-react-typescript/node_modules/apollo-client/index.d.ts
[0] (47,169): error TS2459: Type '{ networkInterface?: NetworkInterface | undefined; reduxRootKey?: string | undefined; reduxRootSe...' has no property 'ssrMode' and no string index signature.
[0] /home/zhenghu/coding/qsc/qsc-main-react-typescript/node_modules/apollo-client/index.d.ts
[0] (47,178): error TS2459: Type '{ networkInterface?: NetworkInterface | undefined; reduxRootKey?: string | undefined; reduxRootSe...' has no property 'ssrForceFetchDelay' and no string index signature.
[0] /home/zhenghu/coding/qsc/qsc-main-react-typescript/node_modules/apollo-client/index.d.ts
[0] (47,198): error TS2459: Type '{ networkInterface?: NetworkInterface | undefined; reduxRootKey?: string | undefined; reduxRootSe...' has no property 'mutationBehaviorReducers' and no string index signature.
[0] /home/zhenghu/coding/qsc/qsc-main-react-typescript/node_modules/apollo-client/index.d.ts
[0] (47,224): error TS2459: Type '{ networkInterface?: NetworkInterface | undefined; reduxRootKey?: string | undefined; reduxRootSe...' has no property 'batchInterval' and no string index signature.
```
### Expected Behavior

No error.
### Version
- apollo-client@0.4.21
- react-apollo@0.5.11

**Comment by Axure** [comment] 2016-10-18 17:36
Looking at the definition:
```
    constructor({networkInterface, reduxRootKey, reduxRootSelector, initialState, dataIdFromObject, queryTransformer, resultTransformer, resultComparator, shouldBatch, ssrMode, ssrForceFetchDelay, mutationBehaviorReducers, batchInterval}?: {
        networkInterface?: NetworkInterface;
        reduxRootKey?: string;
        reduxRootSelector?: string | ApolloStateSelector;
        initialState?: any;
        dataIdFromObject?: IdGetter;
        queryTransformer?: QueryTransformer;
        resultTransformer?: ResultTransformer;
        resultComparator?: ResultComparator;
        shouldBatch?: boolean;
        ssrMode?: boolean;
        ssrForceFetchDelay?: number;
        mutationBehaviorReducers?: MutationBehaviorReducerMap;
        batchInterval?: number;
    });
```
The types aren't really compatible. We have a `?` in the parameter, but no correspondence in the type. Adding a `& undefined` to the type seems to resolve the error.

**Comment by helfer** [comment] 2016-10-26 03:59
Which version of typescript are you using? I haven't seen this error before.

**Comment by kay-is** [comment] 2016-11-15 18:53
I can confirm this. `strictNullChecks: true` is the cause. The definitions probably need to be a bit "stricter" haha.

**Comment by helfer** [comment] 2016-11-15 21:31
Ok, so the solution would be for us to turn `strictNullChecks` on in the tsc options for apollo-client? If that's all that's needed, I'd be happy to accept a PR @Axure @kay-is 🙂

**Comment by ersimont** [comment] 2017-01-08 17:42
I fixed this by manually editing the `.d.ts` file to remove the first `?` from the constructor declaration (at the end of the second line below) to eliminates the errors, and adding a second constructor declaration for the case when nothing is passed in:

```typescript
    constructor();
    constructor({networkInterface, reduxRootKey, reduxRootSelector, initialState, dataIdFromObject, resultComparator, ssrMode, ssrForceFetchDelay, mutationBehaviorReducers, addTypename, resultTransformer, customResolvers, connectToDevTools, queryDeduplication}: {
        networkInterface?: NetworkInterface;
        reduxRootKey?: string;
        reduxRootSelector?: string | ApolloStateSelector;
        initialState?: any;
        dataIdFromObject?: IdGetter;
        resultTransformer?: ResultTransformer;
        resultComparator?: ResultComparator;
        ssrMode?: boolean;
        ssrForceFetchDelay?: number;
        mutationBehaviorReducers?: MutationBehaviorReducerMap;
        addTypename?: boolean;
        customResolvers?: CustomResolverMap;
        connectToDevTools?: boolean;
        queryDeduplication?: boolean;
    });
```

I was going to submit a PR for this, but the `.d.ts` file does not appear to be in the repo? I guess it is generated by some voodoo magic that I have not yet learned.

**Comment by lemonmade** [comment] 2017-01-16 19:35
This is also biting me, also using `strictNullChecks`. I'm just casting to get this to work without copying any definitions around, but would be great to get it resolved in the shipped definitions.

**Closed** 2017-01-19 20:09 UTC
