### ISSUE TITLE
watchQuery polling fails to poll when being called after unsubscribe?

### ISSUE THREAD

**Issue by pmcalmeida** [apollostack/apollo-client#703] opened 2016-09-23 16:04 UTC
I noticed the following pattern when calling the unsubscribe method from a queryObservable.subscribe.
The query stops polling as expected, but when I need to make a new subscription, based on the same query, after executing watchQuery and subscribe, it fetches just once from graphql and then stops polling.
Is there any reason why this behavior is ocurring?

**Comment by pmcalmeida** [comment] 2016-09-23 17:32
This seems to be happening only ocasionally and it could be something related to the implementation in my application, but I've verified that the unsubscribe is not called again after the new subscription. Any thoughts on this would be appreciated.

**Comment by helfer** [comment] 2016-09-23 21:03
@pmcalmeida This could be a bug in apollo client. If you can figure out a reliable way to reproduce it, it would help us pinpoint the issue better.

**Comment by pmcalmeida** [comment] 2016-09-26 16:19
@helfer I wasn't able to successfully replicate this in a isolated environment as it seems to be only happening when being injected in my angular (1.5.x) application when transpiled with babel. In the scheduler object when a watchQuery is run, eveything seemed to be registered correctly.

**Comment by pmcalmeida** [comment] 2016-09-26 19:32
If it helps, while debugging I found that when I tried to create a new subscription it would add the queryId to the intervalQueries instead of creating a new setInterval in the polling timers.
`    QueryScheduler.prototype.addQueryOnInterval = function (queryId, queryOptions) {
        var _this = this;
        var interval = queryOptions.pollInterval;
        if (this.intervalQueries.hasOwnProperty(interval.toString())) {
            this.intervalQueries[interval].push(queryId);
        }
        else {
            this.intervalQueries[interval] = [queryId];
            this.pollingTimers[interval] = setInterval(function () {
                _this.fetchQueriesOnInterval(interval);
            }, interval);
        }
    };`

**Comment by pmcalmeida** [comment] 2016-09-26 21:32
I managed to work around the issue by setting the watchQuery with the same interval as another poller. And verified removing the interval from the intervalQueries when it's empty on https://github.com/apollostack/apollo-client/blob/aa21b02283cf17e399e889f3f122a4feeea829c1/src/scheduler.ts#L129 that it fixes the issue.
`if (this.intervalQueries[interval].length === 0) {
            clearInterval(this.pollingTimers[interval]);
            delete this.intervalQueries[interval];
        }`

**Comment by pmcalmeida** [comment] 2016-09-26 23:05
@helfer I was able to replicate this successfully with the following pattern: 
- watchQuery with a poll interval of 15000 and subscribe
- watchQuery with a poll interval of 20000 and subscribe
- let it run for a minute
- Unsubscribe from the query of 15000 interval
- wait a few seconds
- watchQuery with a poll interval of 15000 and subscribe
- Verify that in the network requests only the first fetch is trigered

Here is an example from a debug in the console:
<img width="901" alt="screen shot 2016-09-27 at 00 04 43" src="https://cloud.githubusercontent.com/assets/7373988/18854836/17503d9e-8446-11e6-8195-bd36349e9c30.png">

**Comment by helfer** [comment] 2016-10-21 00:48
@pmcalmeida can you check if this issue still occurs in 0.5.0-1 of Apollo Client?

**Comment by helfer** [comment] 2016-11-17 18:30
Closing since it's been 4 weeks.

**Closed by helfer** 2016-11-17 18:30 UTC
Labels: bug, needs-repro
