### ISSUE TITLE
Client changes error logging

### ISSUE THREAD

**Issue by purplecones** [apollostack/apollo-client#406] opened 2016-07-15 21:11 UTC
Sorry for unclear title but let me try and explain in more detail. Since starting to use Apollo Client, I've noticed that console errors, when they appear, are not as clear anymore and hard to debug. For example, below is a simple Container/Component. In `render()` I try to access properties that do not exist:`console.log(this.props.propThatDoesNotExist.test)` should throw an error.

**Component**
```javascript
import React from 'react';

class Test extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    console.log(this.props.propThatDoesNotExist.test);
    return <div>test</div>;
  }
}

export default Test;
```

This container does not use Apollo Client. It just resolves and renders the component without attaching anything to `props`.
**Container (*without* Apollo Client)**
```javascript
import { useDeps, composeAll, compose } from 'mantra-core';

import TestComponent from '../components/TestComponent.jsx';

const mapQueryToProps = ({ context }, onData) => {
  onData(null, {});
};

const mapDepsToProps = (context, actions) => ({
  context: () => context,
});

export default composeAll(
  compose(mapQueryToProps),
  useDeps(mapDepsToProps),
)(TestComponent);
```

The error received is expected and very clear.
**Expected error**
```
TestComponent.jsx:9 Uncaught TypeError: Cannot read property 'test' of undefined
```
---
Now let's try the same container with Apollo Client. I should note that Apollo Client works fine in the app and assume that the query is valid and returns data. 
**Container (with Apollo Client)**
```javascript
import { useDeps, composeAll, compose } from 'mantra-core';
import gql from 'graphql-tag';

import TestComponent from '../components/TestComponent.jsx';

const mapQueryToProps = ({ context }, onData) => {
  const { Client } = context();

  Client.query({
    query: gql`
      some query that works
    `,
    forceFetch: true,
  }).then((graphQLResult) => {
    onData(null, {
      data: graphQLResult.data,
      errors: graphQLResult.errors,
      store: Store,
    });
  }).catch((ex) => {
    onData(ex);
  });
};

const mapDepsToProps = (context, actions) => ({
  context: () => context,
});

export default composeAll(
  compose(mapQueryToProps),
  useDeps(mapDepsToProps),
)(TestComponent);
```

The component did not change, but the error is completely different and not clear.
**Unclear error when using Apollo Client**
```
Uncaught (in promise) TypeError: Cannot read property 'getNativeNode' of null(…)
```

I noticed I started getting a lot of `getNativeNode` errors for trivial errors like accessing variables that do not exist. I'm not completely sure how this works and why Apollo Client would affect the way errors are thrown in code that is not Apollo related.

**Comment by stubailo** [comment] 2016-07-19 01:00
Hey, this is a duplicate of this bug (which is in react-apollo, not this package): https://github.com/apollostack/react-apollo/issues/57

Please help identify the cause, we've been trying to track it down for a while since it can be pretty hard to reproduce.

**Closed by stubailo** 2016-07-19 01:00 UTC

**Comment by purplecones** [comment] 2016-07-19 07:32
Thanks @stubailo . I read through the issue you mentioned and it appears to very similar. However, one noticeable difference is that I am **not** using the `react-apollo` but still run into the issue. In fact, I don't have `react-apollo` at all in my `node_modules` folder.

**Comment by stubailo** [comment] 2016-07-19 16:46
Ah, I think it's an issue with react-komposer or whatever Mantra uses then. Basically, the problem is that the rendering is done synchronously inside `onData`, meaning that the network request promise catches all errors from React accidentally.

I'd suggest using `react-apollo` instead, since it's got some really great Apollo-specific functionality that will reduce rerenders, pass through errors and loading state, etc.

Given your code snippet I don't see any advantage to _not_ using the `react-apollo` `connect` - it will even work correctly with `compose`!

**Comment by purplecones** [comment] 2016-07-19 17:15
Thanks @stubailo ! I'll look into your suggestion
