### ISSUE TITLE
Possible unhandled promise rejection

### ISSUE THREAD

**Issue by octohedron** [apollostack/apollo-client#431] opened 2016-07-20 19:16 UTC
I'm trying to work this out, I'm getting an annoying YellowBox warning that reads "Possible Unhandled Promise Rejection: Network error: Network request failed" when running my app without an internet connection for testing purposes.
 [As explained in the docs: "The promise should be rejected in the case of a network error".](http://docs.apollostack.com/apollo-client/network.html)

This is the code, it goes to the catch but it also throws the YellowBox warning, and I'm trying to get rid of it
```javascript
client.query({ query: gql`...`, }).then((data) => {
    console.log(data);
}).catch((error) => {
    console.log(error); // works
});
```

**Comment by stubailo** [comment] 2016-07-20 20:52
Duplicate of: https://github.com/apollostack/apollo-client/issues/423

There's an idea for a fix there, could you submit a PR for it?

**Closed by stubailo** 2016-07-20 20:52 UTC
